version: "3.8"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${APP_PORT:-3000}
    ports:
      - "${BLUE_PORT:-8081}:${APP_PORT:-3000}"
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--spider",
          "http://localhost:${APP_PORT:-3000}/healthz",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${APP_PORT:-3000}
    ports:
      - "${GREEN_PORT:-8082}:${APP_PORT:-3000}"
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--spider",
          "http://localhost:${APP_PORT:-3000}/healthz",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}
      - APP_PORT=${APP_PORT:-3000}
    networks:
      - app_network
    depends_on:
      app_blue:
        condition: service_healthy
      app_green:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  app_network:
    driver: bridge
